services:
  # --- OLLAMA LA LLAMA ---
  ollama-engine:
    image: ollama/ollama:latest
    container_name: ollama_engine
    volumes:
      - ollama_storage:/root/.ollama
    #  iniciar el server
    entrypoint: /bin/sh
    command: -c "/bin/ollama serve & pid=$$!; sleep 5; echo 'ðŸ”´ Descargando modelo llama3...'; ollama pull llama3; echo 'ðŸŸ¢ Modelo listo!'; wait $$pid"
    ports:
      - "11434:11434" # localhost 
    deploy: #  GPU NVIDIA
     resources:
       reservations:
         devices:
           - driver: nvidia
             count: 1
             capabilities: [gpu]
    networks:
      - ai_network
    restart: always

  # --- API FASTAPI xd---
  fastapi-app:
    build: .
    container_name: fastapi_gateway
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      ollama-engine:
        condition: service_started
    networks:
      - ai_network

volumes:
  ollama_storage:

networks:
  ai_network:
    driver: bridge